package org.jprotocol.example.handler;
import org.jprotocol.framework.handler.*;
import org.jprotocol.framework.logger.IProtocolLogger;
import org.jprotocol.framework.logger.IProtocolLogger.NullProtocolLogger;
import org.jprotocol.framework.test.ProtocolMockery;
import org.jprotocol.example.dsl.ClientHandlerHierarchy;
/**
* This class is generated by ClientServerHandlerHierarchyWithMockeryGenerator.groovy
* @author eliasa01
*/
public class ClientHandlerHierarchyWithMockery extends ClientHandlerHierarchy {
    public final ProtocolMockery mockery;
    public ClientHandlerHierarchyWithMockery(final IFlushable flushable, IProtocolLogger logger) {
        this(flushable, logger, new ProtocolSnifferProxy());
    }
    private ClientHandlerHierarchyWithMockery(final IFlushable flushable, IProtocolLogger logger, ProtocolSnifferProxy sniffer) {
        super(flushable, new ProtocolState(), sniffer, logger);
        this.mockery = new ProtocolMockery(getRoot(), new NullProtocolLogger(), true);
        sniffer.init(mockery);
    }
}
