package org.jprotocol.example.handler;
import org.jprotocol.framework.dsl.*;
import org.jprotocol.framework.handler.*;
import org.jprotocol.example.api.*;
/**
* This class is generated by DefaultHandlerGenerator.groovy
* @author Anders Eliasson
*/
public class DefaultMyMiddleProtocolBHandler extends Handler<MyMiddleProtocolB_Request_API, MyMiddleProtocolB_Response_API> {
    protected DefaultMyMiddleProtocolBHandler(HandlerContext context) {
        super(new org.jprotocol.example.dsl.MyMiddleProtocolB(), "MiddleSwitch", "MiddleSwitch", context);
    }
    @Override public final MyMiddleProtocolB_Request_API createRequest(IProtocolMessage p) {
        return new MyMiddleProtocolB_Request_API(p);
    }
    @Override public final MyMiddleProtocolB_Response_API createResponse(IProtocolMessage p) {
        return new MyMiddleProtocolB_Response_API(p);
    }
}
