package org.jprotocol.example.handler;
import org.jprotocol.framework.core.*;
import org.jprotocol.framework.handler.*;
import org.jprotocol.example.api.*;
/**
* This class is generated by DefaultHandlerGenerator.groovy
* @author Anders Eliasson
*/
public class DefaultMyLeafProtocolAHandler extends Handler<MyLeafProtocolA_Request_API, MyLeafProtocolA_Response_API> {
    protected DefaultMyLeafProtocolAHandler(HandlerContext context) {
        super(new org.jprotocol.example.protocols.MyLeafProtocolA(), null, null, context);
    }
    @Override public final MyLeafProtocolA_Request_API createRequest(IProtocolMessage p) {
        return new MyLeafProtocolA_Request_API(p);
    }
    @Override public final MyLeafProtocolA_Response_API createResponse(IProtocolMessage p) {
        return new MyLeafProtocolA_Response_API(p);
    }
}
