package org.jprotocol.example.handler;
import org.jprotocol.framework.core.*;
import org.jprotocol.framework.handler.*;
import org.jprotocol.example.api.*;
import org.jprotocol.framework.logger.IProtocolLogger;
/**
* This class is generated by DefaultHandlerGenerator.groovy
* @author Anders Eliasson
*/
public class DefaultMyRootProtocolHandler extends RootHandler<MyRootProtocol_Request_API, MyRootProtocol_Response_API> {
    protected DefaultMyRootProtocolHandler(HandlerContext context, IFlushable flushable, IProtocolLogger logger) {
        super(new org.jprotocol.example.dsl.MyRootProtocol(), "RootSwitch", "RootSwitchResp", context, flushable, logger);
    }
    @Override public final MyRootProtocol_Request_API createRequest(IProtocolMessage p) {
        return new MyRootProtocol_Request_API(p);
    }
    @Override public final MyRootProtocol_Response_API createResponse(IProtocolMessage p) {
        return new MyRootProtocol_Response_API(p);
    }
}
