package org.jprotocol.framework.handler;
import static org.jprotocol.framework.handler.HandlerDsl.root;
import static org.jprotocol.util.Contract.neverGetHere;

import java.io.IOException;

import org.jprotocol.framework.handler.Handler.Type;
import org.jprotocol.framework.handler.HandlerDsl.UpperHandler;
import org.jprotocol.framework.logger.IProtocolLogger;
/**
* This class is generated by DefaultHierarchyGenerator.groovy
* @author eliasa01
*/
abstract public class AbstractHandlerHierarchy<R extends Handler<?, ?>> {
    protected final Type type;
    protected final boolean msbFirst;
    protected final IProtocolState protocolState;
    protected final IProtocolSniffer sniffer;
    private final R root;
	protected final IProtocolLogger logger;
    public AbstractHandlerHierarchy(Type type, final IFlushable flushable, IProtocolState protocolState, IProtocolSniffer sniffer, IProtocolLogger logger) {
        this.type = type;
        this.msbFirst = false;
        this.sniffer = sniffer;
        this.logger = logger;
        this.protocolState = protocolState;
        this.root = createRoot(flushable);
        try {
			logger.write(this.root);
		} catch (IOException e) {
			neverGetHere(e.getMessage());
		}
    }
    public void init() {
        root(getRoot(), upperHandlers());
    }
    protected final R getRoot() {
        return root;
    }
    public void receive(byte[] data) {
        root.receive(data);
    }
    abstract protected R createRoot(IFlushable flushable);
	
    protected final HandlerContext getRootContext() {
		return new RootHandlerContext(type, msbFirst, protocolState, sniffer);
	}
    abstract protected UpperHandler[] upperHandlers();
}
