package org.jprotocol.example.facade;
import org.jprotocol.example.api.RequestAPIFactory;
import org.jprotocol.example.api.ResponseAPIFactory;
import org.jprotocol.example.handler.ServerHandlerHierarchyWithMockery;
import org.jprotocol.framework.facade.AbstractServerFacade;
import org.jprotocol.framework.handler.Handler.Type;
import org.jprotocol.framework.handler.IFlushable;
import org.jprotocol.framework.logger.IProtocolLogger;
import org.jprotocol.framework.logger.ProtocolLogger;
import org.jprotocol.framework.test.ProtocolMockery;
/**
* This class is generated by DefaultFacadeGenerator.groovy
* @author eliasa01
*/
public class ServerFacade extends AbstractServerFacade {
    private final ServerHandlerHierarchyWithMockery hierarchy;
    private final RequestAPIFactory requestFactory;
    private final ResponseAPIFactory responseFactory;
    public ServerFacade(IFlushable flushable) {
        this(flushable, new ProtocolLogger());
    }
    public ServerFacade(IFlushable flushable, IProtocolLogger logger) {
        super(flushable, Type.Server, logger);
        requestFactory = new RequestAPIFactory();
        responseFactory = new ResponseAPIFactory();
        hierarchy = createHierarchy();
    }
    /**
    * Override to provide specialized implementation
    */
    protected ServerHandlerHierarchyWithMockery createHierarchy() {
        return new ServerHandlerHierarchyWithMockery(flushable, logger);
    }
    public RequestAPIFactory requests() {
        return requestFactory;
    }
    public ResponseAPIFactory responses() {
        return responseFactory;
    }
    @Override protected ProtocolMockery getMockery() {
        return hierarchy.mockery;
    }
    @Override public void receive(byte[] data) {
        hierarchy.receive(data);
    }
}
