package org.jprotocol.example.facade;
import org.jprotocol.framework.facade.AbstractFacade;
import org.jprotocol.framework.handler.IFlushable;
import org.jprotocol.framework.logger.IProtocolLogger;
/**
* This class is generated by DefaultTestFacadeGenerator.groovy
* @author Anders Eliasson
*/
public class TestFacade {
    public final ClientFacade client;
    public final ServerFacade server;
    public TestFacade() {
        this(new IProtocolLogger.NullProtocolLogger(), new IProtocolLogger.NullProtocolLogger());
    }
    public TestFacade(IProtocolLogger clientLogger, IProtocolLogger  serverLogger) {
        FlushableClientServer cf = new FlushableClientServer();
        FlushableClientServer sf = new FlushableClientServer();
        client = createClientFacade(cf, clientLogger);
        server = createServerFacade(sf, serverLogger);
        cf.setTarget(server);
        sf.setTarget(client);
    }
    /**
    * Override to provide a specialized version of ClientFacade
    */
    protected ClientFacade createClientFacade(IFlushable flushable, IProtocolLogger logger) {
        return new ClientFacade(flushable, logger);
    }
    /**
    * Override to provide a specialized version of ServerFacade
    */
    protected ServerFacade createServerFacade(IFlushable flushable, IProtocolLogger logger) {
        return new ServerFacade(flushable, logger);
    }
}
class FlushableClientServer implements IFlushable {
    private AbstractFacade server;
    @Override public void flush(byte[] data) {
        server.receive(data);
    }
    public void setTarget(AbstractFacade server) {
        this.server = server;
    }
}
